#!/bin/bash

# Comprehensive Feature Testing Script for KelabSukan
# This script guides you through testing all app features

set -e

echo "=================================="
echo "KelabSukan Feature Testing"
echo "=================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

SITE_URL="https://kelabsukan.netlify.app"

echo "Testing site: $SITE_URL"
echo ""

# Test 1: Site Accessibility
echo "TEST 1: Site Accessibility"
echo "---------------------------"
echo "Opening $SITE_URL..."
echo ""
echo "✓ Check: Page loads without errors"
echo "✓ Check: Navbar shows 'KelabSukan' brand"
echo "✓ Check: Hero section displays"
echo "✓ Check: Navigation links work"
echo ""
read -p "Press Enter after verifying..."
echo ""

# Test 2: Authentication Flow
echo "TEST 2: Authentication Flow"
echo "----------------------------"
echo "Step 2.1: User Registration"
echo "  - Go to: $SITE_URL/register"
echo "  - Fill in:"
echo "      Name: Test User"
echo "      Email: testuser$(date +%s)@example.com"
echo "      Password: Test123!"
echo "      Confirm Password: Test123!"
echo "  - Click: Sign up"
echo ""
echo "✓ Expected: Account created, redirected to dashboard"
echo "✓ Expected: See 'Welcome back' message"
echo ""
read -p "Press Enter after registering..."
echo ""

echo "Step 2.2: User Login"
echo "  - Logout first (if logged in)"
echo "  - Go to: $SITE_URL/login"
echo "  - Enter credentials"
echo "  - Click: Log in"
echo ""
echo "✓ Expected: Logged in successfully"
echo "✓ Expected: See personalized dashboard"
echo ""
read -p "Press Enter after testing login..."
echo ""

echo "Step 2.3: Logout"
echo "  - Click 'Log out' button in navbar"
echo ""
echo "✓ Expected: Logged out, see login/signup buttons"
echo ""
read -p "Press Enter after testing logout..."
echo ""

# Test 3: Club Management
echo "TEST 3: Club Management"
echo "------------------------"
echo "Step 3.1: Create a Club"
echo "  - Login and go to Profile page"
echo "  - Click: 'Create new club'"
echo "  - Fill in:"
echo "      Club name: My Test Club"
echo "      Description: A club for testing"
echo "      City: Kuala Lumpur"
echo "  - Click: Create club"
echo ""
echo "✓ Expected: Club created, redirected to club page"
echo "✓ Expected: You are marked as owner"
echo ""
read -p "Press Enter after creating club..."
echo ""

echo "Step 3.2: View Club Details"
echo "  - Check club info displays correctly"
echo "  - Check 'Admin controls' panel visible (as owner)"
echo "  - Check upcoming events section"
echo "  - Check recent scores section"
echo ""
echo "✓ Expected: All club data displays correctly"
echo ""
read -p "Press Enter after viewing club..."
echo ""

echo "Step 3.3: Create Event (Admin)"
echo "  - On club page, click 'Create event'"
echo "  - Fill in:"
echo "      Title: Test Game Night"
echo "      Date: Tomorrow 7pm"
echo "      Location: Court 1"
echo "  - Click: Create event"
echo ""
echo "✓ Expected: Event appears in 'Upcoming game days'"
echo ""
read -p "Press Enter after creating event..."
echo ""

# Test 4: Score Recording
echo "TEST 4: Score Recording"
echo "------------------------"
echo "Step 4.1: Record Singles Match"
echo "  - On club page, click 'Record score'"
echo "  - Select: Sport = Badminton"
echo "  - Select: Match type = Singles"
echo "  - Enter: Match title = 'Test Singles Match'"
echo "  - Enter Player 1 name: 'Ali'"
echo "  - Enter Player 2 name: 'Bob'"
echo "  - Enter Score: 21 - 15"
echo "  - Click: Record score"
echo ""
echo "✓ Expected: Success toast appears"
echo "✓ Expected: Match appears in 'Recent scores'"
echo ""
read -p "Press Enter after recording singles match..."
echo ""

echo "Step 4.2: Record Doubles Match"
echo "  - Click 'Record score' again"
echo "  - Select: Match type = Doubles"
echo "  - Enter 4 player names"
echo "  - Enter scores for multiple sets"
echo "  - Click: Record score"
echo ""
echo "✓ Expected: Doubles match saved correctly"
echo ""
read -p "Press Enter after recording doubles match..."
echo ""

echo "Step 4.3: Verify Persistence"
echo "  - Refresh the page"
echo "  - Check if matches are still there"
echo ""
echo "✓ Expected: All recorded matches persist after refresh"
echo ""
read -p "Press Enter after verifying persistence..."
echo ""

# Test 5: Error Handling
echo "TEST 5: Error Handling"
echo "----------------------"
echo "Step 5.1: 404 Page"
echo "  - Go to: $SITE_URL/non-existent-page"
echo ""
echo "✓ Expected: See 'Page not found' message"
echo "✓ Expected: 'Return home' link works"
echo ""
read -p "Press Enter after testing 404..."
echo ""

echo "Step 5.2: Invalid Club ID"
echo "  - Go to: $SITE_URL/club/fake-club-id"
echo ""
echo "✓ Expected: Redirected to 404 page"
echo ""
read -p "Press Enter after testing invalid club..."
echo ""

echo "Step 5.3: Form Validation"
echo "  - Try submitting empty forms"
echo "  - Try mismatched passwords on register"
echo "  - Try duplicate player names in score form"
echo ""
echo "✓ Expected: Appropriate error messages shown"
echo ""
read -p "Press Enter after testing validation..."
echo ""

# Test 6: Responsive Design
echo "TEST 6: Responsive Design"
echo "--------------------------"
echo "  - Open site on mobile or resize browser"
echo "  - Check layout adapts correctly"
echo "  - Check all buttons are clickable"
echo ""
echo "✓ Expected: Site is usable on mobile"
echo ""
read -p "Press Enter after testing responsive..."
echo ""

# Summary
echo ""
echo "=================================="
echo -e "${GREEN}Testing Complete!${NC}"
echo "=================================="
echo ""
echo "Summary of tests:"
echo "  ✓ Site Accessibility"
echo "  ✓ Authentication (Register/Login/Logout)"
echo "  ✓ Club Management (Create/View)"
echo "  ✓ Event Creation"
echo "  ✓ Score Recording (Singles/Doubles)"
echo "  ✓ Data Persistence"
echo "  ✓ Error Handling"
echo "  ✓ Form Validation"
echo "  ✓ Responsive Design"
echo ""
echo "If all tests passed, your app is fully functional!"
echo ""
echo "Next steps:"
echo "  - Invite real users"
echo "  - Create real clubs"
echo "  - Start recording real matches!"
echo ""
